# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/jan/Downloads/mxe/usr/x86_64-pc-linux-gnu/bin/cmake

# The command to remove a file.
RM = /home/jan/Downloads/mxe/usr/x86_64-pc-linux-gnu/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jan/Projects/Personal/Bar/Tabbachi-manager-second

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jan/Projects/Personal/Bar/Tabbachi-manager-second

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/jan/Downloads/mxe/usr/x86_64-pc-linux-gnu/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/jan/Downloads/mxe/usr/x86_64-pc-linux-gnu/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/jan/Downloads/mxe/usr/x86_64-pc-linux-gnu/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/jan/Downloads/mxe/usr/x86_64-pc-linux-gnu/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/jan/Downloads/mxe/usr/x86_64-pc-linux-gnu/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/jan/Downloads/mxe/usr/x86_64-pc-linux-gnu/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/jan/Downloads/mxe/usr/x86_64-pc-linux-gnu/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/jan/Downloads/mxe/usr/x86_64-pc-linux-gnu/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jan/Projects/Personal/Bar/Tabbachi-manager-second/CMakeFiles /home/jan/Projects/Personal/Bar/Tabbachi-manager-second//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jan/Projects/Personal/Bar/Tabbachi-manager-second/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tabbachi-manager-second

# Build rule for target.
Tabbachi-manager-second: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tabbachi-manager-second
.PHONY : Tabbachi-manager-second

# fast build rule for target.
Tabbachi-manager-second/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/build
.PHONY : Tabbachi-manager-second/fast

#=============================================================================
# Target rules for targets named Tabbachi-manager-second_autogen

# Build rule for target.
Tabbachi-manager-second_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tabbachi-manager-second_autogen
.PHONY : Tabbachi-manager-second_autogen

# fast build rule for target.
Tabbachi-manager-second_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second_autogen.dir/build.make CMakeFiles/Tabbachi-manager-second_autogen.dir/build
.PHONY : Tabbachi-manager-second_autogen/fast

Tabbachi-manager-second_autogen/mocs_compilation.obj: Tabbachi-manager-second_autogen/mocs_compilation.cpp.obj
.PHONY : Tabbachi-manager-second_autogen/mocs_compilation.obj

# target to build an object file
Tabbachi-manager-second_autogen/mocs_compilation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/Tabbachi-manager-second_autogen/mocs_compilation.cpp.obj
.PHONY : Tabbachi-manager-second_autogen/mocs_compilation.cpp.obj

Tabbachi-manager-second_autogen/mocs_compilation.i: Tabbachi-manager-second_autogen/mocs_compilation.cpp.i
.PHONY : Tabbachi-manager-second_autogen/mocs_compilation.i

# target to preprocess a source file
Tabbachi-manager-second_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/Tabbachi-manager-second_autogen/mocs_compilation.cpp.i
.PHONY : Tabbachi-manager-second_autogen/mocs_compilation.cpp.i

Tabbachi-manager-second_autogen/mocs_compilation.s: Tabbachi-manager-second_autogen/mocs_compilation.cpp.s
.PHONY : Tabbachi-manager-second_autogen/mocs_compilation.s

# target to generate assembly for a file
Tabbachi-manager-second_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/Tabbachi-manager-second_autogen/mocs_compilation.cpp.s
.PHONY : Tabbachi-manager-second_autogen/mocs_compilation.cpp.s

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.obj: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.obj

# target to build an object file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.cpp.obj

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.i: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.i

# target to preprocess a source file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.cpp.i

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.s: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.s

# target to generate assembly for a file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.cpp.s

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.obj: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.obj

# target to build an object file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.cpp.obj

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.i: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.i

# target to preprocess a source file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.cpp.i

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.s: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.s

# target to generate assembly for a file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.cpp.s

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.obj: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.obj

# target to build an object file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.cpp.obj

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.i: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.i

# target to preprocess a source file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.cpp.i

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.s: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.s

# target to generate assembly for a file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.cpp.s

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.obj: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.obj

# target to build an object file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.cpp.obj

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.i: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.i

# target to preprocess a source file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.cpp.i

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.s: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.s

# target to generate assembly for a file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.cpp.s

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.obj: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.obj

# target to build an object file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.cpp.obj

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.i: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.i

# target to preprocess a source file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.cpp.i

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.s: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.s

# target to generate assembly for a file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.cpp.s

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.obj: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.obj

# target to build an object file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.cpp.obj

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.i: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.i

# target to preprocess a source file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.cpp.i

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.s: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.s

# target to generate assembly for a file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.cpp.s

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.obj: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.obj

# target to build an object file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.cpp.obj

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.i: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.i

# target to preprocess a source file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.cpp.i

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.s: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.s

# target to generate assembly for a file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.cpp.s

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.obj: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.obj

# target to build an object file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.cpp.obj

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.i: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.i

# target to preprocess a source file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.cpp.i

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.s: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.s

# target to generate assembly for a file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.cpp.s

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.obj: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.obj

# target to build an object file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.cpp.obj

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.i: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.i

# target to preprocess a source file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.cpp.i

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.s: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.s

# target to generate assembly for a file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.cpp.s

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.obj: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.obj

# target to build an object file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.cpp.obj

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.i: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.i

# target to preprocess a source file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.cpp.i

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.s: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.s

# target to generate assembly for a file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.cpp.s

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.obj: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.obj

# target to build an object file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.cpp.obj

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.i: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.i

# target to preprocess a source file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.cpp.i

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.s: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.s

# target to generate assembly for a file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.cpp.s

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.obj: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.obj

# target to build an object file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.cpp.obj

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.i: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.i

# target to preprocess a source file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.cpp.i

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.s: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.s

# target to generate assembly for a file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.cpp.s

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.obj: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.obj

# target to build an object file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.cpp.obj

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.i: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.i

# target to preprocess a source file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.cpp.i

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.s: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.s

# target to generate assembly for a file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.cpp.s

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.obj: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.obj

# target to build an object file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.cpp.obj
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.cpp.obj

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.i: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.i

# target to preprocess a source file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.cpp.i
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.cpp.i

home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.s: home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.s

# target to generate assembly for a file
home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.cpp.s
.PHONY : home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.obj: mainwindow.cpp.obj
.PHONY : mainwindow.obj

# target to build an object file
mainwindow.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/mainwindow.cpp.obj
.PHONY : mainwindow.cpp.obj

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tabbachi-manager-second.dir/build.make CMakeFiles/Tabbachi-manager-second.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Tabbachi-manager-second_autogen"
	@echo "... Tabbachi-manager-second"
	@echo "... Tabbachi-manager-second_autogen/mocs_compilation.obj"
	@echo "... Tabbachi-manager-second_autogen/mocs_compilation.i"
	@echo "... Tabbachi-manager-second_autogen/mocs_compilation.s"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.obj"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.i"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.s"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.obj"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.i"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICNSPlugin_Import.s"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.obj"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.i"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.s"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.obj"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.i"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJp2Plugin_Import.s"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.obj"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.i"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.s"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.obj"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.i"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QMngPlugin_Import.s"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.obj"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.i"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgIconPlugin_Import.s"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.obj"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.i"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QSvgPlugin_Import.s"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.obj"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.i"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTgaPlugin_Import.s"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.obj"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.i"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QTiffPlugin_Import.s"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.obj"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.i"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin_Import.s"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.obj"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.i"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWebpPlugin_Import.s"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.obj"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.i"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5Gui_QWindowsIntegrationPlugin_Import.s"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.obj"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.i"
	@echo "... home/jan/Downloads/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5Widgets_QWindowsVistaStylePlugin_Import.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.obj"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

